//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtfDdsSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GtfDdsSharp.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given DDS buffer is too small to convert the specified data..
        /// </summary>
        internal static string Argument_DdsOverflowBytes {
            get {
                return ResourceManager.GetString("Argument_DdsOverflowBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given GTF buffer is too small to convert the specified data..
        /// </summary>
        internal static string Argument_GtfOverflowBytes {
            get {
                return ResourceManager.GetString("Argument_GtfOverflowBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string Argument_InvalidOffLen {
            get {
                return ResourceManager.GetString("Argument_InvalidOffLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was not readable..
        /// </summary>
        internal static string Argument_StreamNotReadable {
            get {
                return ResourceManager.GetString("Argument_StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find texture with ID &apos;{0}&apos;..
        /// </summary>
        internal static string Argument_TextureNotFound {
            get {
                return ResourceManager.GetString("Argument_TextureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of DDS images was not in the range [1, 255]..
        /// </summary>
        internal static string ArgumentOutOfRange_DdsImageCount {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_DdsImageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value was out of legal range..
        /// </summary>
        internal static string ArgumentOutOfRange_Enum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size..
        /// </summary>
        internal static string IO_FileTooLong2GB {
            get {
                return ResourceManager.GetString("IO_FileTooLong2GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is too long. This operation is currently limited to supporting files less than 4 gigabytes in size..
        /// </summary>
        internal static string IO_FileTooLong4GB {
            get {
                return ResourceManager.GetString("IO_FileTooLong4GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DDS file. Image data extends past the end of the file..
        /// </summary>
        internal static string IO_InvalidDds_EOF {
            get {
                return ResourceManager.GetString("IO_InvalidDds_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DDS file. Header cannot be converted to a GTF texture..
        /// </summary>
        internal static string IO_InvalidDdsHeader_Convert {
            get {
                return ResourceManager.GetString("IO_InvalidDdsHeader_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DDS file. Header data extends past the end of the file..
        /// </summary>
        internal static string IO_InvalidDdsHeader_EOF {
            get {
                return ResourceManager.GetString("IO_InvalidDdsHeader_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DDS file. Bad magic number detected..
        /// </summary>
        internal static string IO_InvalidDdsHeader_Magic {
            get {
                return ResourceManager.GetString("IO_InvalidDdsHeader_Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DDS file. Invalid pixel format size detected..
        /// </summary>
        internal static string IO_InvalidDdsHeader_PFSize {
            get {
                return ResourceManager.GetString("IO_InvalidDdsHeader_PFSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DDS file. Invalid header size detected..
        /// </summary>
        internal static string IO_InvalidDdsHeader_Size {
            get {
                return ResourceManager.GetString("IO_InvalidDdsHeader_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF file. File size was not aligned to a 128-byte boundary..
        /// </summary>
        internal static string IO_InvalidGtfFile_Size {
            get {
                return ResourceManager.GetString("IO_InvalidGtfFile_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF file. Header data extends past the end of the file..
        /// </summary>
        internal static string IO_InvalidGtfHeader_EOF {
            get {
                return ResourceManager.GetString("IO_InvalidGtfHeader_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF file. Number of textures was not in the range [1, 255]..
        /// </summary>
        internal static string IO_InvalidGtfHeader_NumTexture {
            get {
                return ResourceManager.GetString("IO_InvalidGtfHeader_NumTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF file. Image size was not aligned to a 128-byte boundary..
        /// </summary>
        internal static string IO_InvalidGtfHeader_Size {
            get {
                return ResourceManager.GetString("IO_InvalidGtfHeader_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF file. Texture attributes extend past the end of the file..
        /// </summary>
        internal static string IO_InvalidGtfHeader_TextureEOF {
            get {
                return ResourceManager.GetString("IO_InvalidGtfHeader_TextureEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF texture. Image data extends past the end of the file..
        /// </summary>
        internal static string IO_InvalidGtfTexture_EOF {
            get {
                return ResourceManager.GetString("IO_InvalidGtfTexture_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF texture. Texture ID was not in the range [0, 255]..
        /// </summary>
        internal static string IO_InvalidGtfTexture_Id {
            get {
                return ResourceManager.GetString("IO_InvalidGtfTexture_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTF texture. Texture offset was not aligned to a 128-byte boundary..
        /// </summary>
        internal static string IO_InvalidGtfTexture_Offset {
            get {
                return ResourceManager.GetString("IO_InvalidGtfTexture_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DX10 DDS files are not supported..
        /// </summary>
        internal static string NotSupported_DX10 {
            get {
                return ResourceManager.GetString("NotSupported_DX10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture format not supported: &apos;{0}&apos;..
        /// </summary>
        internal static string NotSupported_TextureFormat {
            get {
                return ResourceManager.GetString("NotSupported_TextureFormat", resourceCulture);
            }
        }
    }
}
